#!/bin/sh

# This is how it starts...
# Get a json file via wget or curl.
# Then pull the values out of it for each station (or a single station)
#
# eg.  Fetch the vals for first station to match the "disco" tag.
#
#   scriptuner disco 1

# Notice how the url value needs work to get past the colon in http://...
#  and it still needs the bit after the 2nd colon removed if it does not start with a number
#  Or actually just remove any ":homepage" with sed.

jsonValue() {
KEY=$1
num=$2
awk -F"[,:}]" '{for(i=1;i<=NF;i++){if($i~/\042'$KEY'\042/){print $(i+1)}}}' | tr -d '"' | sed -n ${num}p
}

jsonURL() {
KEY=$1
num=$2
awk -F"[,:}]" '{for(i=1;i<=NF;i++){if($i~/\042'$KEY'\042/){print $(i+1) ":" $(i+2) ":" $(i+3)}}}' | tr -d '"' | sed -n ${num}p |sed -e 's/:homepage//' 
}

jsonList() {
num=$1
awk -F"[,:}]" '{for(i=1;i<=NF;i++){\
if($i~/\042'name'\042/){print $(i+1) "... "};\
if($i~/\042'url'\042/){print $(i+1) "... " $(i+3) ":" $(i+4) ":" $(i+5)};\
}}'
}

# Fetch it
rm -f $1
wget "http://www.radio-browser.info/webservice/json/stations/bytag/$1"
# Break into line based records for awk (and readability)
sed -e 's/\\\\\//\//g' -e 's/[{}]/\n/g' $1 >$1.txt
CNT=$(grep "\"id\":\"" $1.txt | wc -l)
echo "Total=$CNT"

cat $1.txt | jsonValue id $2
cat $1.txt | jsonValue name $2
cat $1.txt | jsonURL url $2
cat $1.txt | jsonValue codec $2
cat $1.txt | jsonValue bitrate $2

cat $1.txt | jsonList $2



