#!/bin/sh

# This is how it starts...
# Get a json file via wget or curl.
# Then pull the values out of it for each station (or a single station)
#
# eg.  Fetch the vals for first station to match the "disco" tag.
#
#   scriptuner disco 1

# Notice how the url value needs work to get past the colon in http://...

jsonValue() {
KEY=$1
num=$2
awk -F"[,:}]" '{for(i=1;i<=NF;i++){if($i~/\042'$KEY'\042/){print $(i+1)}}}' | tr -d '"' | sed -n ${num}p
}

wget "http://www.radio-browser.info/webservice/json/stations/bytag/$1"

cat $1 | jsonValue id $2
cat $1 | jsonValue name $2
cat $1 | jsonValue url $2
cat $1 | jsonValue codec $2
cat $1 | jsonValue bitrate $2
